import type { Doctor } from "@/components/cards/doctor-card"
import type { Remedy } from "@/components/cards/remedy-card"
import type { HealingSystem } from "@/components/cards/pathy-card"

export const doctors: Doctor[] = [
  {
    id: "1",
    name: "Dr. Priya Sharma",
    specialty: "Cardiologist",
    experience: 15,
    rating: 4.8,
    reviewCount: 342,
    hospital: "Apollo Hospital, Delhi",
    location: "Delhi",
    distance: "2.5 km",
    availability: "Today, 3:00 PM",
    isAvailable: true,
    imageUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=300&fit=crop",
  },
  {
    id: "2",
    name: "Dr. Rajesh Kumar",
    specialty: "Orthopedic",
    experience: 12,
    rating: 4.7,
    reviewCount: 289,
    hospital: "Max Hospital, Mumbai",
    location: "Mumbai",
    distance: "3.2 km",
    availability: "Tomorrow, 10:00 AM",
    isAvailable: true,
    imageUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=300&fit=crop",
  },
  {
    id: "3",
    name: "Dr. Anita Desai",
    specialty: "Pediatrician",
    experience: 18,
    rating: 4.9,
    reviewCount: 456,
    hospital: "Fortis Hospital, Bangalore",
    location: "Bangalore",
    distance: "1.8 km",
    availability: "Today, 5:30 PM",
    isAvailable: true,
    imageUrl: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&h=300&fit=crop",
  },
  {
    id: "4",
    name: "Dr. Vikram Singh",
    specialty: "Dermatologist",
    experience: 10,
    rating: 4.6,
    reviewCount: 234,
    hospital: "Medanta Hospital, Gurgaon",
    location: "Gurgaon",
    distance: "4.5 km",
    availability: "Tomorrow, 2:00 PM",
    isAvailable: false,
    imageUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&h=300&fit=crop",
  },
  {
    id: "5",
    name: "Dr. Sneha Patel",
    specialty: "Gynecologist",
    experience: 14,
    rating: 4.8,
    reviewCount: 398,
    hospital: "Lilavati Hospital, Mumbai",
    location: "Mumbai",
    distance: "2.8 km",
    availability: "Today, 4:00 PM",
    isAvailable: true,
    imageUrl: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400&h=300&fit=crop",
  },
  {
    id: "6",
    name: "Dr. Amit Verma",
    specialty: "Neurologist",
    experience: 20,
    rating: 4.9,
    reviewCount: 512,
    hospital: "AIIMS, Delhi",
    location: "Delhi",
    distance: "5.0 km",
    availability: "Tomorrow, 11:00 AM",
    isAvailable: true,
    imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=300&fit=crop",
  },
]

export const remedies: Remedy[] = [
  {
    id: "1",
    title: "Cough remedy for cold relief",
    description: "Natural ingredients to soothe your throat and reduce coughing",
    category: "Respiratory",
    imageUrl: "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?w=400&h=250&fit=crop",
    likes: 234,
    comments: 45,
    shares: 12,
    isVerified: true,
  },
  {
    id: "2",
    title: "Wounds with Turmeric Honey Healing",
    description: "Antiseptic properties help heal wounds naturally",
    category: "Skin Care",
    imageUrl: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400&h=250&fit=crop",
    likes: 189,
    comments: 32,
    shares: 8,
    isVerified: true,
  },
  {
    id: "3",
    title: "Ginger Tea for Digestion",
    description: "Traditional remedy for upset stomach and improved digestion",
    category: "Digestive",
    imageUrl: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&h=250&fit=crop",
    likes: 312,
    comments: 67,
    shares: 23,
    isVerified: true,
  },
  {
    id: "4",
    title: "Neem Leaves for Skin Problems",
    description: "Natural antibacterial properties for clear, healthy skin",
    category: "Skin Care",
    imageUrl: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&h=250&fit=crop",
    likes: 198,
    comments: 41,
    shares: 15,
    isVerified: true,
  },
  {
    id: "5",
    title: "Honey and Lemon for Sore Throat",
    description: "Soothing remedy for throat pain and inflammation",
    category: "Respiratory",
    imageUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400&h=250&fit=crop",
    likes: 276,
    comments: 54,
    shares: 19,
    isVerified: true,
  },
  {
    id: "6",
    title: "Tulsi Kadha for Immunity",
    description: "Powerful immune-boosting traditional Indian remedy",
    category: "Immunity",
    imageUrl: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=250&fit=crop",
    likes: 421,
    comments: 89,
    shares: 34,
    isVerified: true,
  },
]

export const healingSystems: HealingSystem[] = [
  {
    id: "allopathy",
    name: "Allopathy",
    principles: ["Evidence-based medicine", "Pharmaceutical drugs", "Surgical interventions"],
    approach: ["Quick symptom relief", "Targeted medication", "Surgery when needed"],
    bestFor: ["Acute conditions", "Bacterial infections", "Emergency care", "Chronic disease management"],
    sideEffects: "Possible side effects",
    timeFrame: "Fast action",
    cost: "Variable",
    prevention: "Moderate",
    color: "blue",
  },
  {
    id: "homeopathy",
    name: "Homeopathy",
    principles: ["Like cures like", "Minimum dose", "Individualized treatment"],
    approach: ["Holistic healing", "Natural substances", "Personalized remedies"],
    bestFor: ["Chronic conditions", "Allergies", "Autoimmune disorders", "Mental health"],
    sideEffects: "Minimal",
    timeFrame: "Gradual improvement",
    cost: "Affordable",
    prevention: "High",
    color: "teal",
  },
  {
    id: "ayurveda",
    name: "Ayurveda",
    principles: ["Balance of doshas", "Natural herbs", "Lifestyle medicine"],
    approach: ["Herbal medicines", "Diet & lifestyle", "Detoxification"],
    bestFor: ["Digestive issues", "Skin conditions", "Stress management", "Preventive care"],
    sideEffects: "Minimal",
    timeFrame: "Moderate",
    cost: "Moderate",
    prevention: "Very high",
    color: "green",
  },
  {
    id: "naturopathy",
    name: "Naturopathy",
    principles: ["Body's healing power", "Natural therapies", "Prevention focus"],
    approach: ["Hydrotherapy", "Mud therapy", "Yoga & meditation"],
    bestFor: ["Lifestyle diseases", "Obesity", "Diabetes", "Hypertension"],
    sideEffects: "None",
    timeFrame: "Gradual",
    cost: "Affordable",
    prevention: "Very high",
    color: "green",
  },
  {
    id: "acupuncture",
    name: "Acupuncture",
    principles: ["Energy flow (Qi)", "Meridian points", "Balance restoration"],
    approach: ["Needle insertion", "Pressure points", "Energy balance"],
    bestFor: ["Pain management", "Migraines", "Arthritis", "Stress relief"],
    sideEffects: "Minimal",
    timeFrame: "Moderate",
    cost: "Moderate",
    prevention: "Moderate",
    color: "orange",
  },
]

export const specialties = [
  "Cardiologist",
  "Dermatologist",
  "Pediatrician",
  "Orthopedic",
  "Gynecologist",
  "Neurologist",
  "Dentist",
  "ENT Specialist",
  "General Physician",
  "Ayurvedic Doctor",
  "Homeopathic Doctor",
]

export const remedyCategories = [
  "All",
  "Respiratory",
  "Digestive",
  "Skin Care",
  "Immunity",
  "Pain Relief",
]
