import type {
  DoctorProfile,
  PatientProfile,
  Appointment,
  ModeratableRemedy,
  ConsultationRecord,
  FamilyMember,
  Notification,
  Payment,
} from "./types"

// Mock patients
export const mockPatients: PatientProfile[] = [
  {
    id: "patient-1",
    email: "rahul.kumar@email.com",
    name: "Rahul Kumar",
    role: "patient",
    phone: "+91 98765 43210",
    dateOfBirth: "1990-05-15",
    bloodGroup: "B+",
    allergies: ["Penicillin"],
    medicalHistory: ["Diabetes Type 2"],
    createdAt: "2024-01-15T10:00:00Z",
    familyMembers: [
      {
        id: "family-1",
        patientId: "patient-1",
        type: "mom",
        name: "Savita Kumar",
        dateOfBirth: "1965-03-20",
        bloodGroup: "B+",
        allergies: [],
        medicalHistory: ["Hypertension"],
        createdAt: "2024-03-10T10:00:00Z",
      },
      {
        id: "family-2",
        patientId: "patient-1",
        type: "baby",
        name: "Arjun Kumar",
        dateOfBirth: "2023-06-15",
        bloodGroup: "B+",
        allergies: [],
        medicalHistory: [],
        createdAt: "2024-03-10T10:00:00Z",
      },
    ],
  },
  {
    id: "patient-2",
    email: "priya.sharma@email.com",
    name: "Priya Sharma",
    role: "patient",
    phone: "+91 98765 43211",
    dateOfBirth: "1985-08-22",
    bloodGroup: "O+",
    allergies: [],
    medicalHistory: ["Hypertension"],
    createdAt: "2024-02-10T10:00:00Z",
    familyMembers: [
      {
        id: "family-3",
        patientId: "patient-2",
        type: "mom",
        name: "Priya Sharma",
        dateOfBirth: "1985-08-22",
        bloodGroup: "O+",
        allergies: [],
        medicalHistory: ["Hypertension"],
        createdAt: "2024-03-10T10:00:00Z",
      },
    ],
  },
  {
    id: "patient-3",
    email: "amit.patel@email.com",
    name: "Amit Patel",
    role: "patient",
    phone: "+91 98765 43212",
    dateOfBirth: "1978-12-03",
    bloodGroup: "A+",
    allergies: ["Sulfa drugs"],
    medicalHistory: ["Asthma"],
    createdAt: "2024-02-20T10:00:00Z",
  },
  {
    id: "patient-4",
    email: "sunita.verma@email.com",
    name: "Sunita Verma",
    role: "patient",
    phone: "+91 98765 43213",
    dateOfBirth: "1995-03-18",
    bloodGroup: "AB+",
    allergies: [],
    medicalHistory: [],
    createdAt: "2024-03-01T10:00:00Z",
  },
  {
    id: "patient-5",
    email: "vikram.singh@email.com",
    name: "Vikram Singh",
    role: "patient",
    phone: "+91 98765 43214",
    dateOfBirth: "1982-07-25",
    bloodGroup: "B-",
    allergies: ["Aspirin"],
    medicalHistory: ["Arthritis"],
    createdAt: "2024-03-05T10:00:00Z",
  },
]

// Mock doctors
export const mockDoctors: DoctorProfile[] = [
  {
    id: "doctor-1",
    email: "dr.anita@curecircle.in",
    name: "Dr. Anita Desai",
    role: "doctor",
    specialization: "Ayurveda",
    clinicName: "Ayush Wellness Center",
    yearsExperience: 18,
    location: "Mumbai, Maharashtra",
    licenseNumber: "BAMS-MH-2006-1234",
    bio: "Experienced Ayurvedic practitioner specializing in chronic disease management and preventive care.",
    consultationFee: 500,
    availability: ["Mon", "Wed", "Fri"],
    isVerified: true,
    verificationStatus: "verified",
    phone: "+91 98765 00001",
    imageUrl: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&h=300&fit=crop",
    createdAt: "2023-06-15T10:00:00Z",
  },
  {
    id: "doctor-2",
    email: "dr.rajesh@curecircle.in",
    name: "Dr. Rajesh Kumar",
    role: "doctor",
    specialization: "Homeopathy",
    clinicName: "Holistic Healing Clinic",
    yearsExperience: 15,
    location: "Delhi",
    licenseNumber: "BHMS-DL-2009-5678",
    bio: "Homeopathic specialist with expertise in treating allergies, skin conditions, and autoimmune disorders.",
    consultationFee: 400,
    availability: ["Tue", "Thu", "Sat"],
    isVerified: false,
    verificationStatus: "pending",
    phone: "+91 98765 00002",
    imageUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=300&fit=crop",
    createdAt: "2023-08-20T10:00:00Z",
  },
  {
    id: "doctor-3",
    email: "dr.priya@curecircle.in",
    name: "Dr. Priya Sharma",
    role: "doctor",
    specialization: "General Medicine",
    clinicName: "City Care Hospital",
    yearsExperience: 12,
    location: "Bangalore, Karnataka",
    licenseNumber: "MBBS-KA-2012-9012",
    bio: "General physician with a holistic approach combining modern medicine with traditional practices.",
    consultationFee: 600,
    availability: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    isVerified: false,
    verificationStatus: "rejected",
    phone: "+91 98765 00003",
    imageUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=300&fit=crop",
    createdAt: "2023-09-10T10:00:00Z",
  },
]

// Get today's date formatted
const today = new Date()
const formatDate = (date: Date) => date.toISOString().split("T")[0]
const tomorrow = new Date(today)
tomorrow.setDate(tomorrow.getDate() + 1)
const dayAfter = new Date(today)
dayAfter.setDate(dayAfter.getDate() + 2)

// Mock appointments with payment status
export const mockAppointments: Appointment[] = [
  {
    id: "apt-1",
    patientId: "patient-1",
    patientName: "Rahul Kumar",
    doctorId: "doctor-1",
    doctorName: "Dr. Anita Desai",
    date: formatDate(today),
    time: "10:00 AM",
    type: "video",
    status: "confirmed",
    reason: "Follow-up for diabetes management",
    createdAt: "2024-03-10T10:00:00Z",
    paymentStatus: "success",
    paymentAmount: 500,
    paymentId: "pay-1",
    statusHistory: [
      { status: "pending", changedAt: "2024-03-10T10:00:00Z", changedBy: "system" },
      { status: "confirmed", changedAt: "2024-03-10T12:00:00Z", changedBy: "doctor-1" },
    ],
  },
  {
    id: "apt-2",
    patientId: "patient-2",
    patientName: "Priya Sharma",
    doctorId: "doctor-1",
    doctorName: "Dr. Anita Desai",
    date: formatDate(today),
    time: "11:30 AM",
    type: "in-person",
    status: "pending",
    reason: "Consultation for joint pain",
    createdAt: "2024-03-11T10:00:00Z",
    paymentStatus: "pending",
    paymentAmount: 500,
    statusHistory: [
      { status: "pending", changedAt: "2024-03-11T10:00:00Z", changedBy: "system" },
    ],
  },
  {
    id: "apt-3",
    patientId: "patient-3",
    patientName: "Amit Patel",
    doctorId: "doctor-1",
    doctorName: "Dr. Anita Desai",
    date: formatDate(today),
    time: "2:00 PM",
    type: "chat",
    status: "confirmed",
    reason: "Skin allergy treatment",
    createdAt: "2024-03-12T10:00:00Z",
    paymentStatus: "success",
    paymentAmount: 500,
    paymentId: "pay-3",
    statusHistory: [
      { status: "pending", changedAt: "2024-03-12T10:00:00Z", changedBy: "system" },
      { status: "confirmed", changedAt: "2024-03-12T14:00:00Z", changedBy: "doctor-1" },
    ],
  },
  {
    id: "apt-4",
    patientId: "patient-4",
    patientName: "Sunita Verma",
    doctorId: "doctor-1",
    doctorName: "Dr. Anita Desai",
    date: formatDate(tomorrow),
    time: "9:00 AM",
    type: "video",
    status: "pending",
    reason: "Initial consultation",
    createdAt: "2024-03-13T10:00:00Z",
    paymentStatus: "failed",
    paymentAmount: 500,
    statusHistory: [
      { status: "pending", changedAt: "2024-03-13T10:00:00Z", changedBy: "system" },
    ],
  },
  {
    id: "apt-5",
    patientId: "patient-5",
    patientName: "Vikram Singh",
    doctorId: "doctor-1",
    doctorName: "Dr. Anita Desai",
    date: formatDate(tomorrow),
    time: "3:30 PM",
    type: "in-person",
    status: "rescheduled",
    reason: "Arthritis pain management",
    createdAt: "2024-03-14T10:00:00Z",
    paymentStatus: "success",
    paymentAmount: 500,
    paymentId: "pay-5",
    rescheduledFrom: formatDate(today),
    rescheduledTo: formatDate(tomorrow),
    statusHistory: [
      { status: "pending", changedAt: "2024-03-14T10:00:00Z", changedBy: "system" },
      { status: "confirmed", changedAt: "2024-03-14T12:00:00Z", changedBy: "doctor-1" },
      { status: "rescheduled", changedAt: "2024-03-15T09:00:00Z", changedBy: "patient-5", reason: "Personal emergency" },
    ],
  },
  {
    id: "apt-6",
    patientId: "patient-1",
    patientName: "Rahul Kumar",
    doctorId: "doctor-1",
    doctorName: "Dr. Anita Desai",
    date: formatDate(dayAfter),
    time: "10:00 AM",
    type: "video",
    status: "cancelled",
    reason: "Monthly check-up",
    createdAt: "2024-03-15T10:00:00Z",
    paymentStatus: "refunded",
    paymentAmount: 500,
    statusHistory: [
      { status: "pending", changedAt: "2024-03-15T10:00:00Z", changedBy: "system" },
      { status: "confirmed", changedAt: "2024-03-15T12:00:00Z", changedBy: "doctor-1" },
      { status: "cancelled", changedAt: "2024-03-16T08:00:00Z", changedBy: "patient-1", reason: "Not available on this date" },
    ],
  },
]

// Mock remedies with moderation status
export const mockModeratableRemedies: ModeratableRemedy[] = [
  // Approved remedies (visible publicly)
  {
    id: "remedy-1",
    title: "Turmeric Honey for Cold Relief",
    description: "A traditional remedy combining the anti-inflammatory properties of turmeric with the soothing effects of honey to relieve cold symptoms.",
    category: "Respiratory",
    ingredients: ["1 tsp turmeric powder", "2 tbsp raw honey", "1 cup warm milk", "Pinch of black pepper"],
    steps: [
      "Heat the milk until warm (not boiling)",
      "Add turmeric powder and mix well",
      "Add honey and black pepper",
      "Drink warm before bedtime"
    ],
    safetyNotes: "Not recommended for children under 1 year due to honey content.",
    benefit: "Relieves cold, cough, and sore throat",
    imageUrl: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400&h=250&fit=crop",
    uploadedBy: "Sunita Devi",
    uploaderId: "user-001",
    uploadedAt: "2024-01-15T10:00:00Z",
    status: "approved",
    reviewedBy: "Dr. Anita Desai",
    reviewedAt: "2024-01-16T14:00:00Z",
    reviewNotes: "Traditional remedy with proven benefits. Safe for most adults.",
    isPublic: true,
    likes: 234,
    comments: 45,
    shares: 12,
  },
  {
    id: "remedy-2",
    title: "Ginger Tea for Digestion",
    description: "Simple ginger tea preparation to aid digestion and relieve stomach discomfort.",
    category: "Digestive",
    ingredients: ["1 inch fresh ginger", "2 cups water", "1 tsp honey", "Half lemon juice"],
    steps: [
      "Peel and slice the ginger",
      "Boil water with ginger for 10 minutes",
      "Strain into a cup",
      "Add honey and lemon juice",
      "Drink warm after meals"
    ],
    safetyNotes: "May interact with blood thinners. Consult doctor if on medication.",
    benefit: "Improves digestion, reduces bloating and nausea",
    imageUrl: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&h=250&fit=crop",
    uploadedBy: "Meera Patel",
    uploaderId: "user-002",
    uploadedAt: "2024-01-20T10:00:00Z",
    status: "approved",
    reviewedBy: "Dr. Rajesh Kumar",
    reviewedAt: "2024-01-21T11:00:00Z",
    reviewNotes: "Well-documented remedy. Added note about blood thinner interaction.",
    isPublic: true,
    likes: 312,
    comments: 67,
    shares: 23,
  },
  {
    id: "remedy-3",
    title: "Neem Paste for Skin",
    description: "Natural neem paste for treating acne and skin infections.",
    category: "Skin Care",
    ingredients: ["Handful of neem leaves", "1 tbsp turmeric", "Rose water as needed"],
    steps: [
      "Wash neem leaves thoroughly",
      "Grind into a paste",
      "Mix with turmeric powder",
      "Add rose water to make smooth paste",
      "Apply on affected areas for 20 minutes",
      "Wash with lukewarm water"
    ],
    safetyNotes: "Do a patch test first. Not for use during pregnancy.",
    benefit: "Treats acne, reduces inflammation, antibacterial",
    imageUrl: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&h=250&fit=crop",
    uploadedBy: "Kavita Sharma",
    uploaderId: "user-003",
    uploadedAt: "2024-02-01T10:00:00Z",
    status: "approved",
    reviewedBy: "Dr. Priya Sharma",
    reviewedAt: "2024-02-02T09:00:00Z",
    reviewNotes: "Effective natural remedy. Added pregnancy caution.",
    isPublic: true,
    likes: 189,
    comments: 32,
    shares: 8,
  },
  // Pending remedies (awaiting review)
  {
    id: "remedy-4",
    title: "Tulsi Kadha for Immunity",
    description: "Traditional immunity-boosting drink using holy basil and spices.",
    category: "Immunity",
    ingredients: ["10-12 tulsi leaves", "1 inch ginger", "4-5 black peppercorns", "2 cloves", "1 cinnamon stick", "2 cups water", "Jaggery to taste"],
    steps: [
      "Boil water with all ingredients except jaggery",
      "Simmer for 15 minutes",
      "Strain and add jaggery",
      "Drink warm twice daily"
    ],
    safetyNotes: "Not recommended during pregnancy. May lower blood sugar.",
    benefit: "Boosts immunity, fights infections",
    imageUrl: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=250&fit=crop",
    uploadedBy: "Ramesh Gupta",
    uploaderId: "user-004",
    uploadedAt: "2024-03-10T10:00:00Z",
    status: "pending",
    isPublic: false,
    likes: 0,
    comments: 0,
    shares: 0,
  },
  {
    id: "remedy-5",
    title: "Ajwain Water for Gas Relief",
    description: "Quick relief from gas and bloating using carom seeds.",
    category: "Digestive",
    ingredients: ["1 tsp ajwain seeds", "1 cup water", "Pinch of black salt"],
    steps: [
      "Dry roast ajwain seeds lightly",
      "Boil with water for 5 minutes",
      "Add black salt",
      "Drink warm after meals"
    ],
    safetyNotes: "Safe for most people. Avoid excessive use.",
    benefit: "Relieves gas, bloating, and indigestion",
    imageUrl: "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?w=400&h=250&fit=crop",
    uploadedBy: "Ananya Reddy",
    uploaderId: "user-005",
    uploadedAt: "2024-03-12T10:00:00Z",
    status: "pending",
    isPublic: false,
    likes: 0,
    comments: 0,
    shares: 0,
  },
  {
    id: "remedy-6",
    title: "Coconut Oil for Hair Growth",
    description: "Traditional hair oiling treatment for stronger, healthier hair.",
    category: "Hair Care",
    ingredients: ["3 tbsp coconut oil", "5-6 curry leaves", "1 tsp fenugreek seeds"],
    steps: [
      "Heat coconut oil on low flame",
      "Add curry leaves and fenugreek seeds",
      "Heat until seeds turn dark",
      "Cool and strain",
      "Massage into scalp",
      "Leave overnight and wash"
    ],
    safetyNotes: "May cause allergic reaction in some. Patch test recommended.",
    benefit: "Promotes hair growth, reduces hair fall",
    imageUrl: "https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=400&h=250&fit=crop",
    uploadedBy: "Lakshmi Iyer",
    uploaderId: "user-006",
    uploadedAt: "2024-03-14T10:00:00Z",
    status: "pending",
    isPublic: false,
    likes: 0,
    comments: 0,
    shares: 0,
  },
  // Rejected remedy
  {
    id: "remedy-7",
    title: "Questionable Weight Loss Mixture",
    description: "A mixture claimed to cause rapid weight loss.",
    category: "Weight Loss",
    ingredients: ["Unknown herb", "Apple cider vinegar", "Cayenne pepper"],
    steps: [
      "Mix all ingredients",
      "Drink on empty stomach"
    ],
    safetyNotes: "",
    benefit: "Claims to lose 10kg in a week",
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=250&fit=crop",
    uploadedBy: "Anonymous User",
    uploaderId: "user-007",
    uploadedAt: "2024-03-08T10:00:00Z",
    status: "rejected",
    reviewedBy: "Dr. Anita Desai",
    reviewedAt: "2024-03-09T10:00:00Z",
    reviewNotes: "Unrealistic claims. Unknown ingredient poses safety risk. Rejected for public safety.",
    isPublic: false,
    likes: 0,
    comments: 0,
    shares: 0,
  },
]

// Mock consultation records
export const mockConsultationRecords: ConsultationRecord[] = [
  {
    id: "consult-1",
    patientId: "patient-1",
    patientName: "Rahul Kumar",
    doctorId: "doctor-1",
    doctorName: "Dr. Anita Desai",
    date: "2024-02-15",
    diagnosis: "Type 2 Diabetes - Well controlled",
    prescription: "Continue Metformin 500mg, Ayurvedic supplement Diabecon",
    consultationNotes: "Patient shows good progress with diet modifications. HbA1c improved from 7.8 to 6.9. Advised to continue current regimen and increase physical activity.",
    followUpDate: "2024-03-15",
    createdAt: "2024-02-15T11:00:00Z",
  },
  {
    id: "consult-2",
    patientId: "patient-2",
    patientName: "Priya Sharma",
    doctorId: "doctor-1",
    doctorName: "Dr. Anita Desai",
    date: "2024-02-20",
    diagnosis: "Hypertension with joint pain",
    prescription: "Ashwagandha tablets, Guggul for joint support",
    consultationNotes: "Blood pressure slightly elevated. Recommended stress management through yoga. Joint pain likely due to early arthritis. Started on Ayurvedic joint support.",
    followUpDate: "2024-03-20",
    createdAt: "2024-02-20T14:00:00Z",
  },
  {
    id: "consult-3",
    patientId: "patient-3",
    patientName: "Amit Patel",
    doctorId: "doctor-1",
    doctorName: "Dr. Anita Desai",
    date: "2024-03-01",
    diagnosis: "Allergic dermatitis",
    prescription: "Neem capsules, Turmeric supplements, External neem oil application",
    consultationNotes: "Skin rash triggered by seasonal allergens. Prescribed internal and external treatments. Advised to avoid known allergens and maintain skin hygiene.",
    followUpDate: "2024-03-15",
    createdAt: "2024-03-01T10:00:00Z",
  },
]

// Mock notifications
export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    userId: "patient-1",
    type: "confirmation",
    title: "Appointment Confirmed",
    message: "Your appointment with Dr. Anita Desai on March 21 at 10:00 AM has been confirmed.",
    link: "/appointments",
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(), // 30 min ago
  },
  {
    id: "notif-2",
    userId: "patient-1",
    type: "payment",
    title: "Payment Successful",
    message: "Payment of Rs. 500 for your consultation with Dr. Anita Desai was successful.",
    link: "/appointments",
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(), // 1 hour ago
  },
  {
    id: "notif-3",
    userId: "patient-1",
    type: "remedy_approval",
    title: "Remedy Approved",
    message: "Your submitted remedy 'Turmeric Honey for Cold Relief' has been approved by our medical team.",
    link: "/remedies",
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), // 1 day ago
  },
  {
    id: "notif-4",
    userId: "patient-1",
    type: "appointment_reminder",
    title: "Upcoming Appointment",
    message: "Reminder: You have a video consultation with Dr. Anita Desai tomorrow at 10:00 AM.",
    link: "/appointments",
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(), // 2 days ago
  },
  {
    id: "notif-5",
    userId: "doctor-1",
    type: "booking",
    title: "New Appointment Request",
    message: "Rahul Kumar has requested an appointment for March 22 at 10:00 AM.",
    link: "/doctor/appointments-list",
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(), // 15 min ago
  },
  {
    id: "notif-6",
    userId: "doctor-1",
    type: "general",
    title: "Pending Remedy Review",
    message: "You have 3 pending remedy submissions waiting for your review.",
    link: "/doctor/remedy-reviews",
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), // 2 hours ago
  },
  {
    id: "notif-7",
    userId: "doctor-1",
    type: "cancellation",
    title: "Appointment Cancelled",
    message: "Rahul Kumar has cancelled their appointment scheduled for March 23.",
    link: "/doctor/appointments-list",
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(), // 5 hours ago
  },
]

// Mock payments
export const mockPayments: Payment[] = [
  {
    id: "pay-1",
    appointmentId: "apt-1",
    patientId: "patient-1",
    doctorId: "doctor-1",
    amount: 500,
    currency: "INR",
    status: "success",
    paymentMethod: "card",
    transactionId: "TXN123456789",
    createdAt: "2024-03-10T10:30:00Z",
    updatedAt: "2024-03-10T10:30:00Z",
  },
  {
    id: "pay-3",
    appointmentId: "apt-3",
    patientId: "patient-3",
    doctorId: "doctor-1",
    amount: 500,
    currency: "INR",
    status: "success",
    paymentMethod: "upi",
    transactionId: "TXN123456791",
    createdAt: "2024-03-12T14:30:00Z",
    updatedAt: "2024-03-12T14:30:00Z",
  },
  {
    id: "pay-5",
    appointmentId: "apt-5",
    patientId: "patient-5",
    doctorId: "doctor-1",
    amount: 500,
    currency: "INR",
    status: "success",
    paymentMethod: "netbanking",
    transactionId: "TXN123456793",
    createdAt: "2024-03-14T12:30:00Z",
    updatedAt: "2024-03-14T12:30:00Z",
  },
]

// Demo credentials for testing
export const demoCredentials = {
  doctor: {
    email: "dr.anita@curecircle.in",
    password: "doctor123",
  },
  patient: {
    email: "rahul.kumar@email.com",
    password: "patient123",
  },
}
